services:  #services syntax comples the creation of cont from img via docfile , assigns network , assigns volumes as well.
  nginxfrontendconone:
      build: puppy/
      ports: 
          - '80:80' 
      container_name: static
      volumes: 
         - myapp:/usr/share/nginx/html/
  nginxfrontendcontwo:
      build: counter/
      ports: 
          - '81:80'
      volumes: 
        - myapp2:/usr/share/nginx/html/ 
      container_name: static2
volumes:   # will create a volume for you.
      myapp:
      myapp2:



